# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x02pb\"\x07\n\x05\x45mpty\"\x1d\n\nCheckReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\"\xa9\x01\n\x13StartProcessRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12-\n\x03\x65nv\x18\x03 \x03(\x0b\x32 .pb.StartProcessRequest.EnvEntry\x12\x0b\n\x03\x63wd\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"X\n\x14StartProcessResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"+\n\x10PostFilesRequest\x12\x17\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x08.pb.File\")\n\x04\x46ile\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\":\n\x11PostFilesResponse\x12\x16\n\x0euploaded_count\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"1\n\x0fGetFileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa4\x02\n\x0c\x41gentService\x12(\n\x0bHealthCheck\x12\t.pb.Empty\x1a\x0e.pb.CheckReply\x12\x39\n\x0e\x45xecuteCommand\x12\x12.pb.CommandRequest\x1a\x13.pb.CommandResponse\x12\x41\n\x0cStartProcess\x12\x17.pb.StartProcessRequest\x1a\x18.pb.StartProcessResponse\x12\x38\n\tPostFiles\x12\x14.pb.PostFilesRequest\x1a\x15.pb.PostFilesResponse\x12\x32\n\x07GetFile\x12\x12.pb.GetFileRequest\x1a\x13.pb.GetFileResponseB\x07Z\x05./;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./;pb'
  _globals['_STARTPROCESSREQUEST_ENVENTRY']._loaded_options = None
  _globals['_STARTPROCESSREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_CHECKREPLY']._serialized_start=28
  _globals['_CHECKREPLY']._serialized_end=57
  _globals['_COMMANDREQUEST']._serialized_start=59
  _globals['_COMMANDREQUEST']._serialized_end=106
  _globals['_COMMANDRESPONSE']._serialized_start=108
  _globals['_COMMANDRESPONSE']._serialized_end=141
  _globals['_STARTPROCESSREQUEST']._serialized_start=144
  _globals['_STARTPROCESSREQUEST']._serialized_end=313
  _globals['_STARTPROCESSREQUEST_ENVENTRY']._serialized_start=271
  _globals['_STARTPROCESSREQUEST_ENVENTRY']._serialized_end=313
  _globals['_STARTPROCESSRESPONSE']._serialized_start=315
  _globals['_STARTPROCESSRESPONSE']._serialized_end=403
  _globals['_POSTFILESREQUEST']._serialized_start=405
  _globals['_POSTFILESREQUEST']._serialized_end=448
  _globals['_FILE']._serialized_start=450
  _globals['_FILE']._serialized_end=491
  _globals['_POSTFILESRESPONSE']._serialized_start=493
  _globals['_POSTFILESRESPONSE']._serialized_end=551
  _globals['_GETFILEREQUEST']._serialized_start=553
  _globals['_GETFILEREQUEST']._serialized_end=587
  _globals['_GETFILERESPONSE']._serialized_start=589
  _globals['_GETFILERESPONSE']._serialized_end=638
  _globals['_AGENTSERVICE']._serialized_start=641
  _globals['_AGENTSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)