app:
  name: conch

log:
  level: info
  # output: "stdout" - only output to stdout
  # output: "file" - only output to file
  # output: "both" - output to both stdout and file
  output: stdout

server:
  host: 0.0.0.0
  port: 4063


