app:
  name: conch

log:
  level: info
  # output: "stdout" - only output to stdout
  # output: "file" - only output to file
  # output: "both" - output to both stdout and file
  output: stdout

server:
  host: 0.0.0.0
  port: 4063

network:
  # CIDR capacity: 4093 slots; practical max depends on host/kernel/network setup. Default: 250
  pool_size: 250
  # If setting dynamic reservation to true, then there is a background thread keep filling the pool till it reaches the max size set above
  dynamic_reservation: false

containerd:
  socket: /run/containerd/containerd.sock
  default_namespace: default
