sandbox:
  api_url: "http://localhost:4063"                # *Sandbox service API endpoint
  workdir_prefix: "/tmp/sandbox_"                 # *Prefix for sandbox working directory
  use_snapshot: false                             # *Whether to use snapshot for sandbox creation (default:false)
  sandbox_id: ""                                  # Optional: sandbox ID (default:auto generate)

snapshot:
  snapshot_id: ""                                 # Snapshot ID (default:auto generate)
  vmm_name: "cloud-hypervisor"                    # *Virtual machine monitor name
  vcpu_num: 1                                     # *Number of virtual CPUs
  ram_mb: 1024                                    # *Memory size in MB

image:
  image_name: ""                                  # *Image name
  vmm_name: "cloud-hypervisor"                    # *Virtual machine monitor name
  vcpu_num: 1                                     # *Number of virtual CPUs
  ram_mb: 1024                                    # *Memory size in MB
