import os
import subprocess
import sys
import fileinput
import logging
import shutil

from setuptools import setup, Command
from setuptools.command.install import install
from setuptools.command.develop import develop

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

SDK_DIR = os.path.dirname(os.path.abspath(__file__))  # sdk directory
API_DIR_REL = "../api"                                # relative path of api directory to sdk
API_DIR_ABS = os.path.abspath(os.path.join(SDK_DIR, API_DIR_REL))
PY_PROTO_DIR_ABS = os.path.join(API_DIR_ABS, "py_proto")
PY_PROTO_DIR_REL = os.path.join(API_DIR_REL, "py_proto")

# Proto file paths
PROTO_SRC_ABS = os.path.join(API_DIR_ABS, "agent.proto")
GRPC_FILE_ABS = os.path.join(PY_PROTO_DIR_ABS, "agent_pb2_grpc.py")
PB2_FILE_ABS = os.path.join(PY_PROTO_DIR_ABS, "agent_pb2.py")

if not os.path.exists(API_DIR_ABS):
    raise FileNotFoundError(f"API directory not found: {API_DIR_ABS}\nPlease confirm the relative path '../api' is correct")
if not os.path.exists(PROTO_SRC_ABS):
    raise FileNotFoundError(f"Proto file not found: {PROTO_SRC_ABS}\nPlease check if agent.proto exists")

os.makedirs(PY_PROTO_DIR_ABS, exist_ok=True)

class BuildProto(Command):
    description = "Generate proto code from agent.proto"
    user_options = []

    def initialize_options(self): pass
    def finalize_options(self): pass

    def run(self):
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"

        PYTHON_EXEC = sys.executable  # use current python interpreter
        original_cwd = os.getcwd()
        conch_dir = os.path.dirname(API_DIR_ABS)
        os.chdir(conch_dir)
        logger.info(f"Switched working directory to Conch root: {conch_dir}")

        protoc_cmd = [
            PYTHON_EXEC,
            "-m", "grpc_tools.protoc",
            f"--proto_path={API_DIR_ABS}",
            f"--python_out={PY_PROTO_DIR_ABS}",
            f"--grpc_python_out={PY_PROTO_DIR_ABS}",
            PROTO_SRC_ABS
        ]
        logger.info(f"Executing Proto compilation command: {' '.join(protoc_cmd)}")

        try:
            result = subprocess.run(
                protoc_cmd,
                env=env,
                capture_output=True,
                text=True,
                check=True
            )
            logger.info(f"Proto compilation stdout: {result.stdout}")
            logger.info("Proto compilation succeeded")
        except subprocess.CalledProcessError as e:
            logger.error(f"Proto compilation failed! Exit code: {e.returncode}")
            logger.error(f"stderr: {e.stderr}")
            logger.error(f"stdout: {e.stdout}")
            raise
        except FileNotFoundError:
            logger.error(
                "grpc_tools not found! Please install manually first: pip install grpcio-tools>=1.57.0",
                exc_info=True
            )
            raise
        except Exception as e:
            logger.error(f"Unknown error occurred during Proto compilation: {e}", exc_info=True)
            raise
        finally:
            os.chdir(original_cwd)
            logger.info(f"Restored working directory to: {original_cwd}")

        if not os.path.exists(PB2_FILE_ABS):
            raise RuntimeError(f"agent_pb2.py not generated! Check protoc command or agent.proto syntax")
        if not os.path.exists(GRPC_FILE_ABS):
            raise RuntimeError(f"agent_pb2_grpc.py not generated! Check protoc command or agent.proto syntax")

        init_file = os.path.join(PY_PROTO_DIR_ABS, "__init__.py")
        if not os.path.exists(init_file):
            with open(init_file, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by setup.py\n")
                f.write("from . import agent_pb2, agent_pb2_grpc\n")
            logger.info(f"Auto-created __init__.py: {init_file}")

        self.fix_grpc_import()  # fix agent_pb2_grpc.py import

    def fix_grpc_import(self):
        if not os.path.exists(GRPC_FILE_ABS):
            raise RuntimeError(f"GRPC file missing: {GRPC_FILE_ABS} (compilation failed)")

        old_import = "import agent_pb2 as agent__pb2"
        new_import = "from . import agent_pb2 as agent__pb2"  # relative import

        logger.info(f"Fixing GRPC import path: {GRPC_FILE_ABS}")

        backup_file = f"{GRPC_FILE_ABS}.bak"
        shutil.copy2(GRPC_FILE_ABS, backup_file)

        with open(GRPC_FILE_ABS, 'r', encoding='utf-8') as f:
            content = f.read()
        content = content.replace(old_import, new_import)
        with open(GRPC_FILE_ABS, 'w', encoding='utf-8') as f:
            f.write(content)

        if os.path.exists(backup_file):
            os.remove(backup_file)
            logger.info(f"Deleted backup file: {backup_file}")

class InstallProto(install):
    def run(self):
        logger.info("Compiling Proto before installation...")
        self.run_command("build_proto")
        install.run(self)

class DevelopProto(develop):
    def run(self):
        logger.info("Compiling Proto before development mode installation...")
        self.run_command("build_proto")
        develop.run(self)

setup(
    name="Conch",
    version="0.1.0",
    packages=["Conch"],
    package_dir={
        "Conch": ".",  # Map Conch main package to sdk directory
    },
    package_data={
    },

    setup_requires=[
        "setuptools>=42.0.0"
    ],

    install_requires=[
        "requests>=2.25.0",
        "grpcio>=1.57.0",
        "protobuf>=4.21.0",
        "PyYAML>=5.4.0",
        "grpcio-tools>=1.57.0"
    ],
    python_requires=">=3.8",
    description="SDK for conch service",
    url="https://atomgit.com/openeuler/Conch",
    cmdclass={
        "build_proto": BuildProto,
        "install": InstallProto,
        "develop": DevelopProto
    },
    # disable zip packaging to avoid import failure of dynamically generated files
    zip_safe=False
)